// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLZ9r3RKWw8Xa-ED7PhtIuDYmotMY4sik',
    appId: '1:327460977805:web:e90b13e2b773a0d954f6c4',
    messagingSenderId: '327460977805',
    projectId: 'foodapp-add66',
    authDomain: 'foodapp-add66.firebaseapp.com',
    storageBucket: 'foodapp-add66.firebasestorage.app',
    measurementId: 'G-2F2YVH3Z0W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtAsJGYEehIggBbs-AXXrmnxJxwhA1IOg',
    appId: '1:327460977805:android:6df061e0a09e80d754f6c4',
    messagingSenderId: '327460977805',
    projectId: 'foodapp-add66',
    storageBucket: 'foodapp-add66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdDeTBJVVfeoHTPxC8OtLReGMd6ZHKfjc',
    appId: '1:327460977805:ios:179bd413989ab04554f6c4',
    messagingSenderId: '327460977805',
    projectId: 'foodapp-add66',
    storageBucket: 'foodapp-add66.firebasestorage.app',
    iosBundleId: 'com.example.foodOrderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdDeTBJVVfeoHTPxC8OtLReGMd6ZHKfjc',
    appId: '1:327460977805:ios:179bd413989ab04554f6c4',
    messagingSenderId: '327460977805',
    projectId: 'foodapp-add66',
    storageBucket: 'foodapp-add66.firebasestorage.app',
    iosBundleId: 'com.example.foodOrderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLZ9r3RKWw8Xa-ED7PhtIuDYmotMY4sik',
    appId: '1:327460977805:web:2148118f531d934554f6c4',
    messagingSenderId: '327460977805',
    projectId: 'foodapp-add66',
    authDomain: 'foodapp-add66.firebaseapp.com',
    storageBucket: 'foodapp-add66.firebasestorage.app',
    measurementId: 'G-DK2FD0YGK1',
  );

}